/**
 * Playwright configuration — pointed at the yieldWerx PROBE Lab app
 * (probe-lab-app/). The webServer seeds and runs the lightweight app
 * (API :5000 + web :3000); the single chromium project runs the BDD scenarios
 * generated by playwright-bdd from features/ + steps/.
 */
import os from 'node:os';

import { defineConfig, devices } from '@playwright/test';
import { defineBddConfig } from 'playwright-bdd';

import { loadConfig } from './src/core/config';
import { VISUAL_BASELINE_TEMPLATE } from './src/core/visual';
import { ALLURE_CATEGORIES } from './src/reporting/allureCategories';

const config = loadConfig();

const bddTestDir = defineBddConfig({
  features: 'features/**/*.feature',
  steps: 'steps/**/*.ts',
});

export default defineConfig({
  testDir: bddTestDir,
  // Removes the LOT-E2E-* wafers the suite uploads, so a developer database does
  // not fill up run after run. Never fails the run — see src/core/global-teardown.ts.
  globalTeardown: './src/core/global-teardown.ts',
  timeout: 30_000,
  expect: { timeout: 10_000 },
  fullyParallel: false,
  retries: 0,
  reporter: [
    ['list'],
    ['html', { open: 'never', outputFolder: 'reports/playwright-report' }],
    ['junit', { outputFile: 'reports/junit.xml' }],
    // Turns each failed scenario into a deduplicated bug candidate under
    // .probe/artifacts/bug-sync/candidates, which `npm run bug:sync` files to
    // Jira. It only writes on failure, so a green run produces nothing.
    ['./src/core/bugCandidateReporter.ts'],
    /*
     * Allure — writes reports/allure-results per test; `npm run allure:generate`
     * (or allure:open / allure:serve) renders it. environmentInfo makes each
     * report self-describing so trend history does not blend runs from
     * different environments; categories classifies a red run into legible
     * buckets (src/reporting/allureCategories.ts).
     */
    [
      'allure-playwright',
      {
        resultsDir: 'reports/allure-results',
        environmentInfo: {
          Environment: process.env.E2E_ENV ?? 'local',
          Base_URL: config.baseUrl,
          OS: `${os.platform()} ${os.release()}`,
          Node: process.version,
          CI: process.env.CI ?? 'false',
        },
        categories: ALLURE_CATEGORIES,
      },
    ],
  ],
  /*
   * Visual baselines live in a committed directory, decoupled from the
   * generated BDD test dir (.features-gen is gitignored, so a template derived
   * from {testDir} would put baselines somewhere git never sees). The template
   * itself is pinned in src/core/visual.ts beside the odiff tolerances, and the
   * framework-selftest project fails if either drifts.
   */
  snapshotPathTemplate: VISUAL_BASELINE_TEMPLATE,
  use: {
    baseURL: config.baseUrl,
    testIdAttribute: 'data-testid',
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  webServer: {
    command: 'cd probe-lab-app && npm start',
    url: 'http://localhost:3000',
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
    stdout: 'pipe',
    stderr: 'pipe',
  },
  projects: [
    {
      name: 'chromium',
      // @visual scenarios only make sense inside the pinned container, so the
      // everyday project never selects them (see src/core/visual.ts).
      grepInvert: /@visual/,
      use: { ...devices['Desktop Chrome'] },
    },
    /**
     * Pixel regression for the canvas charts, compared with odiff. Runs ONLY
     * inside the pinned Playwright container (npm run test:visual) — the
     * @visual step skips host runs, because host-rendered pixels differ per
     * GPU and font stack and must never gate anything.
     */
    {
      name: 'visual',
      testDir: bddTestDir,
      grep: /@visual/,
      use: { ...devices['Desktop Chrome'] },
    },
    /**
     * Framework self-tests: plain specs (no browser, no app) that fail when a
     * pinned framework setting drifts — today, the visual tolerances and
     * baseline path. Runs everywhere, including the host.
     */
    {
      name: 'framework-selftest',
      testDir: './tests/selftest',
    },
  ],
});
