/**
 * Playwright configuration — pointed at the yieldWerx PROBE Lab app
 * (probe-lab-app/). The webServer seeds and runs the lightweight app
 * (API :5000 + web :3000); the single chromium project runs the BDD scenarios
 * generated by playwright-bdd from features/ + steps/.
 */
import { defineConfig, devices } from '@playwright/test';
import { defineBddConfig } from 'playwright-bdd';

import { loadConfig } from './src/core/config';

const config = loadConfig();

const bddTestDir = defineBddConfig({
  features: 'features/**/*.feature',
  steps: 'steps/**/*.ts',
});

export default defineConfig({
  testDir: bddTestDir,
  // Removes the LOT-E2E-* wafers the suite uploads, so a developer database does
  // not fill up run after run. Never fails the run — see src/core/global-teardown.ts.
  globalTeardown: './src/core/global-teardown.ts',
  timeout: 30_000,
  expect: { timeout: 10_000 },
  fullyParallel: false,
  retries: 0,
  reporter: [
    ['list'],
    ['html', { open: 'never', outputFolder: 'reports/playwright-report' }],
    ['junit', { outputFile: 'reports/junit.xml' }],
  ],
  use: {
    baseURL: config.baseUrl,
    testIdAttribute: 'data-testid',
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  webServer: {
    command: 'cd probe-lab-app && npm start',
    url: 'http://localhost:3000',
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
    stdout: 'pipe',
    stderr: 'pipe',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
