/**
 * UI contract drift check (frontend-embedded mode only) — second of the
 * three UI change-detection scripts (gen-ui-contract → check-ui-contract →
 * ui-change-impact; see docs/ui-change-detection.md).
 *
 * WHY: locator policy P1 makes `data-testid` the framework's primary
 * contract with the application; when the framework lives next to the
 * frontend source, a removed/renamed testId can and should fail at the
 * developer's desk instead of as a red E2E run hours later.
 *
 * HOW: verifies that the frontend source PROVIDES every data-testid the
 * framework CONSUMES (per ui-contract.json), scoped to the page objects
 * bound to this frontend in ui-impact-map.json. A missing/renamed testId
 * fails the check (exit 1) and names the consuming page object plus the
 * impacted scenarios and manual cases — so the developer fixes tests (or the
 * rename) BEFORE pushing. The provision scan is careful to distinguish
 * providing an attribute from merely SELECTING on it — see
 * `collectProvidedTestIds`.
 *
 * Standalone framework repos (no frontend next to the tests) are out of
 * scope: without a resolvable frontendRoot this exits 0 with a notice.
 *
 * Run:  npm run ui:check          (uses frontendRoot from ui-impact-map.json)
 *       npm run ui:check -- --frontend <path>
 */
import fs from 'node:fs';
import path from 'node:path';

const REPO_ROOT = process.cwd();

/** File extensions scanned for testId provision — markup plus every JS/TS/SFC flavor. */
const FRONTEND_EXTENSIONS = new Set(['.html', '.js', '.jsx', '.ts', '.tsx', '.vue', '.svelte']);

/**
 * Relevant subset of ui-impact-map.json (hand-maintained binding file):
 * where the frontend lives, which frontend path prefixes map to which page
 * objects, and each page object's downstream impact (tags, feature files,
 * manual cases).
 */
interface ImpactMap {
  frontendRoot?: string;
  frontendGlobs?: Record<string, string[]>;
  pageMap?: Record<string, { tags?: string[]; features?: string[]; cases?: string[] }>;
}

/** Relevant subset of ui-contract.json (generated by `npm run ui:contract`). */
interface UiContract {
  testIds: Record<string, { consumers: string[]; pattern?: true }>;
}

/**
 * Parse a repo-root-relative JSON file, or null when absent (absence is a
 * meaningful state here: no contract → hard error, no impact map →
 * standalone mode).
 *
 * @param rel - Path relative to the repo root.
 */
function readJson<T>(rel: string): T | null {
  const abs = path.join(REPO_ROOT, rel);
  if (!fs.existsSync(abs)) return null;
  return JSON.parse(fs.readFileSync(abs, 'utf-8')) as T;
}

/**
 * Recursively list frontend source files under a directory, skipping
 * node_modules and dot-directories, keeping only FRONTEND_EXTENSIONS.
 *
 * @param dir - Absolute directory to walk.
 */
function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (FRONTEND_EXTENSIONS.has(path.extname(entry.name))) out.push(full);
  }
  return out;
}

/**
 * All testIds the frontend PROVIDES: markup/JSX attributes + setAttribute
 * calls.
 *
 * Two patterns are collected per file:
 * - `data-testid="x"` / `data-testid={'x'}` attribute forms (HTML and JSX);
 * - `setAttribute('data-testid', 'x')` for DOM-built elements.
 *
 * Careful distinction: CSS/query attribute-selector strings like
 * `[data-testid="x"]` are CONSUMPTION, not provision — the negative
 * lookbehind `(?<!\[)` on the attribute regex excludes anything preceded by
 * `[`. A selector string must never satisfy the contract, or a renamed
 * attribute would go undetected (the frontend's own querySelector would
 * "prove" the id exists while the real attribute is gone).
 *
 * @param frontendRoot - Absolute path of the frontend source tree to scan.
 * @returns The set of testId strings the frontend actually renders.
 */
function collectProvidedTestIds(frontendRoot: string): Set<string> {
  const provided = new Set<string>();
  const attribute = /(?<!\[)data-testid\s*=\s*(?:["']([\w-]+)["']|\{\s*["']([\w-]+)["']\s*\})/g;
  const setAttr = /setAttribute\(\s*['"]data-testid['"]\s*,\s*['"]([\w-]+)['"]/g;
  for (const file of walk(frontendRoot)) {
    const source = fs.readFileSync(file, 'utf-8');
    for (const m of source.matchAll(attribute)) {
      const id = m[1] ?? m[2];
      if (id !== undefined) provided.add(id);
    }
    for (const m of source.matchAll(setAttr)) if (m[1] !== undefined) provided.add(m[1]);
  }
  return provided;
}

/*
 * CLI entry (npm run ui:check). Flow: resolve the frontend root (--frontend
 * override, else ui-impact-map.json) → missing contract is a hard failure,
 * missing frontend is a benign standalone-mode notice → collect provided ids
 * → for each contract id consumed by a page object BOUND to this frontend
 * (via frontendGlobs), require provision; dynamic patterns and unbound
 * consumers are skipped, not failed. On failure, print each missing id with
 * its consumers, impacted features/cases, and the exact re-run command, then
 * exit 1.
 */
if (require.main === module) {
  const argIndex = process.argv.indexOf('--frontend');
  const override = argIndex >= 0 ? process.argv[argIndex + 1] : undefined;

  const map = readJson<ImpactMap>('ui-impact-map.json');
  const contract = readJson<UiContract>('ui-contract.json');
  const frontendRel = override ?? map?.frontendRoot;
  const frontendAbs = frontendRel !== undefined ? path.join(REPO_ROOT, frontendRel) : undefined;

  if (contract === null) {
    process.stdout.write('ui-contract.json not found — run `npm run ui:contract` first.\n');
    process.exitCode = 1;
  } else if (frontendAbs === undefined || !fs.existsSync(frontendAbs)) {
    process.stdout.write(
      'UI contract check: no frontend found (frontend-embedded mode only).\n' +
        'This framework is running standalone — the check is n/a here. When\n' +
        'embedded in a frontend repo, set "frontendRoot" in ui-impact-map.json.\n',
    );
  } else {
    // Only page objects BOUND to this frontend are enforceable.
    const boundConsumers = new Set(Object.values(map?.frontendGlobs ?? {}).flat());
    const provided = collectProvidedTestIds(frontendAbs);

    const missing: Array<{ id: string; consumers: string[] }> = [];
    let checked = 0;
    let skipped = 0;
    for (const [id, entry] of Object.entries(contract.testIds)) {
      const bound = entry.consumers.filter((c) => boundConsumers.has(c));
      if (entry.pattern === true || bound.length === 0) {
        skipped++;
        continue; // dynamic pattern, or consumer targets a screen this frontend doesn't implement
      }
      checked++;
      if (!provided.has(id)) missing.push({ id, consumers: bound });
    }

    process.stdout.write(
      `UI contract check — frontend: ${frontendRel}\n` +
        `  required testIds checked: ${checked} · provided by frontend: ${provided.size} · not applicable here: ${skipped}\n`,
    );
    if (missing.length === 0) {
      process.stdout.write('  PASS — the frontend provides every required data-testid.\n');
    } else {
      process.stdout.write(
        `\n  FAIL — ${missing.length} required data-testid(s) missing from the frontend:\n`,
      );
      for (const m of missing) {
        process.stdout.write(`\n  ✖ data-testid="${m.id}"\n`);
        for (const consumer of m.consumers) {
          process.stdout.write(`      consumed by: ${consumer}\n`);
          const impact = map?.pageMap?.[consumer];
          if (impact) {
            if (impact.features?.length)
              process.stdout.write(`      breaks scenarios in: ${impact.features.join(', ')}\n`);
            if (impact.cases?.length)
              process.stdout.write(`      stale manual cases: ${impact.cases.join(', ')}\n`);
            if (impact.tags?.length)
              process.stdout.write(
                `      re-run after fixing: npx bddgen && npx playwright test --project=chromium --grep "${impact.tags.join('|')}"\n`,
              );
          }
        }
      }
      process.stdout.write(
        '\n  Fix the rename in the frontend OR update the page objects + test cases\n' +
          '  (then regenerate the manifest: npm run ui:contract) BEFORE pushing.\n',
      );
      process.exitCode = 1;
    }
  }
}
